site_name: David Sinden
title: blog
description: "This is my blog."
site_url: "https://djps.github.io"
twitter_username: david_sinden
github_username:  djps
theme: simplex
pages:
- Research: 'research.md'
- About Me: 'index.md'
- Code: 'code.md'
